version: '2.3'

services:

  main-service:
    build: .
    container_name: core-service
    environment:
      - JDBC_URL = 'jdbc:postgresql://postgres_test_db:5432/bank'
    depends_on:
      - postgres_test_db
    ports:
      - "9090:9090"

  postgres_test_db:
    image: postgres:13.2
    container_name: postgres_test_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=bank
    ports:
      - "5432:5432"